import Joi from 'joi';

export const createProductSchema = Joi.object({
  name: Joi.string().required(),
  slug: Joi.string().required(),
  description: Joi.string().allow('', null),
  shortDescription: Joi.string().allow('', null),
  price: Joi.number().required().min(0),
  originalPrice: Joi.number().min(0).allow(null),
  discount: Joi.number().min(0).max(100).allow(null),
  categoryId: Joi.string().required(),
  image: Joi.string().allow('', null),
  images: Joi.array().items(Joi.string()).allow(null),
  rating: Joi.number().min(0).max(5).allow(null),
  reviewCount: Joi.number().min(0).allow(null),
  isBestSeller: Joi.boolean(),
  isNew: Joi.boolean(),
  stock: Joi.number().min(0).allow(null),
  packageSize: Joi.string().allow('', null),
  seedCount: Joi.number().min(0).allow(null),
  howToPlant: Joi.string().allow('', null),
});

export const updateProductSchema = Joi.object({
  name: Joi.string(),
  slug: Joi.string(),
  description: Joi.string().allow('', null),
  shortDescription: Joi.string().allow('', null),
  price: Joi.number().min(0),
  originalPrice: Joi.number().min(0).allow(null),
  discount: Joi.number().min(0).max(100).allow(null),
  categoryId: Joi.string(),
  image: Joi.string().allow('', null),
  images: Joi.array().items(Joi.string()).allow(null),
  rating: Joi.number().min(0).max(5).allow(null),
  reviewCount: Joi.number().min(0).allow(null),
  isBestSeller: Joi.boolean(),
  isNew: Joi.boolean(),
  stock: Joi.number().min(0).allow(null),
  packageSize: Joi.string().allow('', null),
  seedCount: Joi.number().min(0).allow(null),
  howToPlant: Joi.string().allow('', null),
});
